language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env:
         - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"
before_install:
    - eval "${MATRIX_EVAL}"
install:
    - sudo apt-get install libboost-all-dev

script: g++ -I /usr/lib/ -lboost_system -lboost_filesystem -o mydu *.cpp